### ISSUE TITLE
Problem with system dark mode

### ISSUE THREAD

**Issue by delnyn** [lucide-icons/lucide#101]
## Prerequisites

* Version: The website actual prod
* Are you running from source/master: Yes
* Are you using a released build: Ofc lol
* Operating system: Windows
* Bits: 64

## Step to reproduce

1. Use system dark mode
2. Erase dark mode's local storage
3. Reload page

### Actual behavior

The search bar, the "download all" button and the hovered cards are illegible.

## Resources

![image](https://user-images.githubusercontent.com/45879791/96404793-1227af00-11dc-11eb-9a04-b8e73d8bce98.png)

**Comment by locness3** [comment]
Same happens for me when using the Dark Website Forcer extension.

**Comment by ericfennis** [comment]
Yeah this is a known issue from the CharkaUI library with NextJs.
@johnletey looked in to it: [thread](https://github.com/chakra-ui/chakra-ui/issues/305#issuecomment-643612615)

I tried to fix it, because they use Nextjs as well on their own website. But the fix they used, they didn't released it yet, [the fix](https://github.com/chakra-ui/chakra-ui/blob/f36aca5085822f9c6352730d8b30a5be43366df6/website/pages/_document.tsx#L10)  
I will keep an eye on it.

**Comment by ericfennis** [comment]
Fixed in #99
