### ISSUE TITLE
Organize Lucide in separate repos

### ISSUE THREAD

**Issue by delnyn** [lucide-icons/lucide#107]
I'm not really working on anything else than icons, but IMO we shouldn't use only 1 repository (e.g. icons, npm package, etc...)

**Comment by ericfennis** [comment]
No a monorepo is ideal for managing it all.

**Why?**
Because you have one single source of truth.

Benefits According to [this article from Alexander Noel](https://www.toptal.com/front-end/guide-to-monorepos) :
- One place to store all configs and tests.
- Easily refactor global features with atomic commits
- Simplified package publishing.
- Easier dependency management.
- Re-use code with shared packages while still keeping them isolated.

Off-course there are some disadvantages, but that happens more if the project gets too big.
(also described in that article)

Here some famous big projects that using monorepos, because of the monorepo advantages
- [Babel](https://github.com/babel/babel)
- [Vue](https://github.com/vuejs/vue)
- [React](https://github.com/facebook/react)

**Comment by delnyn** [comment]
Oh okay
