### ISSUE TITLE
Lucide Vue 3 Next 3

### ISSUE THREAD

**Issue by sobchenyuk** [lucide-icons/lucide#1133]
Good afternoon, I offer my variant of using your package Lucide framewerk NUXT3

`// Icon.ts`
```
import * as icons from "lucide-vue-next";
import {h, computed} from "vue";

interface PropsType {
  name: string,
  size?: number,
  color?: string,
  strokeWidth?: string,
  defaultClass?: string
}
export default {
  props: {
    name: {
      type: String,
      required: true
    },
    size: Number,
    color: String,
    strokeWidth: String,
    defaultClass: String
  },
  setup({ name, color, size, defaultClass, strokeWidth }: PropsType) {
    const getNameListIcons = computed(() => name ? Object.keys(icons).includes(name) : false)
    return () => {
      if (!name || !getNameListIcons.value) {
        return h('span', { style: "color: red" },'Icon Not Found!')
      }
      // @ts-ignore
      return h('div', [h(icons[name], { color, size, defaultClass, strokeWidth })])
    }
  }
}




```

**Comment by ericfennis** [comment]
@sobchenyuk Thanks for sharing, but this kind of example is already written in our documentation. See: https://lucide.dev/docs/lucide-vue-next#one-generic-icon-component

:warning: Big note:  We don't recommend this at all, because this is not supporting tree-shaking. That means that if you do this you will always bundle all lucide icons when building your application, adding 900+ icons in your bundle. Since you maybe use 0 to 10 icons per page. Nuxt has a bundler that does an excellent job in tree-shaking per page. So this is not very efficient.
