### ISSUE TITLE
Not all icons load when using lucide-vue-next

### ISSUE THREAD

**Issue by romaniedelp** [lucide-icons/lucide#1147]
## Prerequisites

* Version: 0.171.0
* Are you running from source/main: 
* Are you using a released build:
* Operating system:  MacOS
* Bits:

### Actual behavior

We are using the lucide-vue-next package in our vue3 application. But when we use this piece of code ( see screenshot ) not all icons are loaded , we wanted to use the tower-control icon in our component but it does not render.

As a first step, we ran the icons in the console in the browser, which shows that tower-control is not in the list.

We have already updated lucid to the latest version, but that did not bring a solution.

Could there be a problem with the lucide-vue-next package?

## Any message or error
![Screenshot 2023-04-24 at 10 47 07](https://user-images.githubusercontent.com/98807720/233946463-96a3b92e-cef0-4029-83fd-f31d00ba96ca.png)
![Screenshot 2023-04-24 at 10 54 00](https://user-images.githubusercontent.com/98807720/233948047-f33a7223-4e6b-41dc-9038-95ee0e7fe265.png)

**Comment by karsa-mistmere** [comment]
Firstly, I got your example working with no problem see this minimal reproduction on StackBlitz:
https://stackblitz.com/edit/vue3-app-5atkak?file=src%2FApp.vue,src%2Fcomponents%2FLucideIcon.vue

Are you sure you're using the correct name? The Vue package exports this icon as `TowerControl`, if you want to use the kebab-case names (e.g. `tower-control`, you'll have to implement case conversion).

---

Secondly, using the package as above is _not recommended_, as this solution will not be able to use tree shaking and your app's performance will suffer, we actually have a warning about this in the documentation.
For what you're trying to implement, you could pass the icons themselves to your custom component instead, something similar as in this example (although you might as well just use the components themselves, since they do support adding extra attributes such as in your example `fill`):
https://stackblitz.com/edit/vue3-app-3e3xja?file=src%2FApp.vue,src%2Fcomponents%2FLucideIcon.vue

**Comment by karsa-mistmere** [comment]
In your designated version, the export is definitely there: https://www.npmjs.com/package/lucide-vue-next/v/0.171.0?activeTab=code

Can you confirm the package version as it appears in your `package-lock.json` or `pnpm-lock.yaml`?

**Comment by romaniedelp** [comment]
> In your designated version, the export is definitely there: https://www.npmjs.com/package/lucide-vue-next/v/0.171.0?activeTab=code see `dist/lucide-vue-next.d.ts`
> 
> Can you confirm the package version as it appears in your `package-lock.json` or `pnpm-lock.yaml` etc?

Jaa sure, we are using this version 

![Screenshot 2023-04-24 at 11 57 20](https://user-images.githubusercontent.com/98807720/233964164-2a7d66af-67ee-4fe0-bc2e-776c0ee31aec.png)

**Comment by karsa-mistmere** [comment]
Again, not as it appears in your `package.json` but the lock file corresponding to your package manager of choice.

**Comment by karsa-mistmere** [comment]
I think you might need to delete the Vite cache: https://vitejs.dev/guide/dep-pre-bundling.html#caching

**Comment by romaniedelp** [comment]
> Again, not as it appears in your `package.json` but the lock file corresponding to your package manager of choice.

My bad, this is the version in the package-lock.json "^0.115.0"

**Comment by romaniedelp** [comment]
@karsa-mistmere  thanks for your help!!
