### ISSUE TITLE
Different weather icons

### ISSUE THREAD

**Issue by cjh9** [lucide-icons/lucide#146]
Sorry for posting so many issues, thank you for a great fork!! Exactly what I've been looking for. I have some more suggestions for weather icons:

Hot weather: A thermometer with a sun
Windy weather: Three curvy strokes that looks like someone is blowing.
Heavy showers: Cloud with rain that goes diagonally,
Cold temperature: Thermometer with a snowflake.
Clear night: Moon but with two stars, one small and one a bit larger. 
Partly cloudy: Cloud with sun in the back.
Thunderstorm: Cloud with a lightning.

Suggestion:
Nicer looking cloud and snowflake.
The original clouds doesn't look very nice, it's hard to see that they are clouds. Do them a bit like this instead, and also the snowflake.

![cloud](https://user-images.githubusercontent.com/18718330/99889603-10c42900-2c57-11eb-8b28-f65dbeaa6f4a.gif)
![snow](https://user-images.githubusercontent.com/18718330/99889604-115cbf80-2c57-11eb-9594-ea3839c43518.gif)

**Comment by Andreto** [comment]
@cjh9 Like @locness3 mentioned in another issue, most of these are probably a bit too specific for the lucide icon set. I'll have a go at it tho and if I manage to do some good ones I can post the code in another repo.

**Comment by ericfennis** [comment]
Some of them I think we already have, some are I think are too specific and some are I think are good ideas

Windy weather: I think [`wind`](https://lucide.netlify.app/icon/wind) can be used here.
Heavy showers: This one is a good idea, maybe a variation from the icon from @Andreto in #117 ?
Cold temperature: Too specific.
Clear night: Too specific?.
Partly cloudy: This one is good idea. -> `cloud-sun`
Thunderstorm: Can't this one be used? [`cloud-lightning`](https://lucide.netlify.app/icon/cloud-lightning).

**Comment by ericfennis** [comment]
@cjh9 @Andreto @locness3 
I rethought this issue. I think some weather icons are welcome. Would lovely to see if there someone makes a weather application using lucide. The current ones aren't suitable for this purpose because we missing a lot of icons.

I followed the icons that apple uses see this [thread](https://discussions.apple.com/thread/6114620), Because we can't use color we can't make difference between night and day icons.

Here are the icons I designed and I refactored some with our guidelines
![image](https://user-images.githubusercontent.com/11825403/104470790-631c2900-55ba-11eb-81de-dae193226cd5.png)
