### ISSUE TITLE
Moon phases

### ISSUE THREAD

**Issue by dsvoid** [lucide-icons/lucide#1463]
## Icon Request

* Icon name: `moon-new` `moon-waxing-crescent` `moon-first-quarter` `moon-waxing-gibbous` `moon-full`  `moon-waning-gibbous` `moon-last-quarter` `moon-waning-crescent`
* Use case: displaying the current phase of the moon in applications and sites that usually display it, e.g. calendar, astrology, and weather services.
* _Screenshots_ of similar icons: https://static.thenounproject.com/png/11882-200.png

To avoid using a fill, perhaps a hatched, dotted, or lined pattern could be used to provide the shading for the unlit portion of the moon.

**Comment by dsvoid** [comment]
A personal first run as an idea: `full-moon` can be represented with the existing circle. I don't think the size of the gap in the two gibbous icons is considered ok since it creates a very small white space, and rotating the lined pattern for the shadow didn't help much either. Perhaps another approximation of shading could work, or replacing shading with a dotted line pattern for the unlit side.

Another option would be to not have a shadow at all, although this would create ambiguity between waxing and waning. Ultimately, I'd rather the guidelines be followed and the icons not exist within the pack.

`moon-new`
![moon1-00-new](https://github.com/lucide-icons/lucide/assets/7375973/de622667-b2ca-4d6e-9e93-e0445526545a)

`moon-waxing-crescent`
![moon1-01-waxing-crescent](https://github.com/lucide-icons/lucide/assets/7375973/6f011399-0168-4f10-a983-2e60822f5779)

`moon-first-quarter`
![moon1-02-first-quarter](https://github.com/lucide-icons/lucide/assets/7375973/d8ea3b3d-55ab-4cdd-8627-40f5c80986cf)

`moon-waxing-gibbous`
![moon1-03-waxing-gibbous](https://github.com/lucide-icons/lucide/assets/7375973/7981f3f1-15a6-4d32-95b8-830a7fb2451c)

`moon-waning-gibbous`
![moon1-05-waning-gibbous](https://github.com/lucide-icons/lucide/assets/7375973/f02ca3de-cba6-4d55-8706-6cfd3fb524ee)

`moon-last-quarter`
![moon1-06-last-quarter](https://github.com/lucide-icons/lucide/assets/7375973/abb467d8-51d3-4170-aefd-6fb6ed73cb9f)

`moon-waning-crescent`
![moon1-07-waning-crescent](https://github.com/lucide-icons/lucide/assets/7375973/e369791d-98fc-4b9c-a32f-e8e2aff5a531)

**Comment by danielbayley** [comment]
@dsvoid See also `eclipse` in https://github.com/lucide-icons/lucide/pull/1280#issuecomment-1549433462.

**Comment by karsa-mistmere** [comment]
Hey @dsvoid,

Thank you for submitting this icon request. The thing is, we do not currently support fills (please refer to #458), crosshatching and similar patterns mimicking them are sadly not an acceptable alternative, since they do not scale well with either icon size nor stroke width. Nonetheless, I think we would happy to add these as soon as we add support for filled icons, up until then, I'm closing this as not planned, but marking them with a dedicated tag so they can be reopened later on).

---

I'm also leaving this Figma file here with some initial drafts for future filled versions, once we can finally support these: https://www.figma.com/file/A7K6e8DjdQDZOEHwry3yNl/lucide%2Fmoon-phases?type=design&node-id=0%3A1&mode=design&t=Mq1L0fEUkpPn4Mkt-1

**Comment by jguddas** [comment]
An option could be to not show the part that's in the shadow

![icon](https://github.com/lucide-icons/lucide/assets/25524993/e4b0ae7b-6db4-4d21-a71c-81641dd0b4cb)

**Comment by karsa-mistmere** [comment]
> An option could be to not show the part that's in the shadow

I did think of that, unfortunately that still would not allow to differentiate between a full moon and a new moon.

**Comment by jguddas** [comment]
> I did think of that, unfortunately that still would not allow to differentiate between a full moon and a new moon.

`circle-dashed` -> `moon-crescent` -> `moon-half` -> `moon-gibbous` -> `circle`

**Comment by karsa-mistmere** [comment]
It's not quite that easy, since a moon not only waxes but also wanes, but I guess in principle that could kinda work, although it's a bit sub-optimal, I don't like the lack of consistency between different stages & new moon, but using dashed parts is a bit funky as well:
![image](https://github.com/lucide-icons/lucide/assets/17746067/151450c1-fa14-45d2-b3f6-7aa8f9656ae7)

**Comment by jguddas** [comment]
> but using dashed parts is a bit funky as well

Looks pretty good IMO.

We don't need the waning ones, they are just flipped, and we don't create flipped versions.

**Comment by karsa-mistmere** [comment]
> Looks pretty good IMO.

As the one who designed them I disagree. 😄 

> We don't need the waning ones, they are just flipped, and we don't create flipped versions.

Um... sure we do, we have all kinds of "up/down/right/left" variants for a whole lot of icons.

**Comment by RjManhas** [comment]
Hello, sorry for commenting but I was also looking into moon icons and where theses added?

**Comment by karsa-mistmere** [comment]
> Hello, sorry for commenting but I was also looking into moon icons and where theses added?

They weren't and are very unlikely to be. The dashed icons are simply not up to par, and we cannot yet support fills, I'm closing this issue again until we do.

**Comment by jguddas** [comment]
@karsa-mistmere can you post the svgs for the dashed version so people can still use theme by taking them from here?

**Comment by karsa-mistmere** [comment]
> @karsa-mistmere can you post the svgs for the dashed version so people can still use theme by taking them from here?

I've added them to the Figma file above.
