### ISSUE TITLE
A 'miscellaneous' icon

### ISSUE THREAD

**Issue by BeetMacol** [lucide-icons/lucide#1560]
### Icon name

miscellaneous

### Use cases

The icon could be used in various lists of categories where some items do not fit any category.

### Design ideas

I do not have any good proposals and haven't found any good design in other sets. The only idea that comes up to my mind regarding its design is to simply put few random shapes that are difficult to associate with any real object.

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by jguddas** [comment]
Ellipses would also work.

**Comment by BeetMacol** [comment]
`shapes` could work, but a dedicated `misc` icon would be much better in my opinion. `elipsis` wouldn't work in some cases as users would expect more categories to pop up when clicked instead of a single "other" category.

I'm not an active user and have never contributed, so I don't want to decide whether `shapes` is good enough to close this – I'll leave the decision to you or other real contributors.

**Comment by karsa-mistmere** [comment]
People could also use an [`asterisk`](https://lucide.dev/icons/asterisk) or [`square-asterisk`](https://lucide.dev/icons/square-asterisk) as "wildcard", or a question mark as "unknown"/"uncategorized".

I think one of these suggestions (including `shapes` and `ellipses`) should be able to work in most instances. Since no specific use case was provided that could help pinpoint this request, I'm closing this, as I do not currently feel the need of adding any extra icons for this use case.
