### ISSUE TITLE
Type errors in svelte with typescript

### ISSUE THREAD

**Issue by dxlbnl** [lucide-icons/lucide#1601]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [ ] lucide-react-native
- [ ] lucide-solid
- [X] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.286.0

### Browser

- [ ] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [X] Other/not relevant

### Operating system

- [ ] Windows
- [X] Linux
- [ ] macOS
- [ ] Other/not relevant

### Description

I've got a svelte-kit typescript project, and when using lucide-svelte I'm getting typescript errors in my .svelte files.

```
Argument of type 'typeof Bold' is not assignable to parameter of type 'ConstructorOfATypedSvelteComponent'.
  Type 'typeof Bold' provides no match for the signature 'new (args: { target: any; props?: any; }): ATypedSvelteComponent'.
```

I'm suspecting the types not being setup properly.

### Steps to reproduce

1. setup a sveltekit typescript project `npm init svelte@next`
2. Install lucide-svelte
3. Add an icon in a component
4. See the ts error in vscode

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by menghif** [comment]
I just looked into this issue and the reason why you get a type error is because you are using an old version of Svelte.

`npm init svelte@next` uses Svelte version 3 instead of version 4.

There was a change in Svelte 4 where `SvelteComponentTyped` was [deprecated](https://svelte.dev/docs/v4-migration-guide#sveltecomponenttyped-is-deprecated) in favour of `SvelteComponent`.

To create a new Svelte 4 project you can use `npm create svelte@latest myapp`, but if you need to stay on Svelte 3, you will have to change `SvelteComponent` to `SvelteComponentTyped` in `lucide-svelte.d.ts`.

Hope this helps!

**Comment by dxlbnl** [comment]
Ohh, that makes sense. I don't need svelte 3, ill be upgrading, which i should've done in the first place.

**Comment by ericfennis** [comment]
See comment from @menghif
