### ISSUE TITLE
[icon request] Outline or hierarchy 

### ISSUE THREAD

**Issue by zoharma** [lucide-icons/lucide#1859]
### Icon name

outline

### Use cases

This is when a button to show hierarchical content is needed. 

### Design ideas

<img width="24" alt="outline" src="https://github.com/lucide-icons/lucide/assets/10050573/93dbe745-af57-4ea2-a640-8dd68554cfe0">

SVG:
![outline](https://github.com/lucide-icons/lucide/assets/10050573/ea5ed0de-1de5-407a-81e2-a174b84bcede)

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by chessurisme** [comment]
The `list` might be helpful in your case for outline.
![list](https://github.com/lucide-icons/lucide/assets/137697011/54f99651-ce75-46d2-b956-36db3309aa6b)

If that is not your case, tell us why?

> Here's the proposed icon: 
![multilevel-line](https://github.com/lucide-icons/lucide/assets/137697011/f3113d89-9aea-48fc-bf4a-c1872cfd71a9)

**Comment by karsa-mistmere** [comment]
To represent hierarchy I would probably use `list-tree` or `network`. While I don't fully understand the use case ("button to show hierarchical content"), if it's for some sort of page/document outline toggle button `menu`, some other `list` icon, or even `panel-left/right` could also work.

That being said, I understand, why you might want a different icon here, I'm just not entirely sure the proposal is legible enough to represent hierarchy, since there are no two items at the same level, so to me it feels somewhat more like some kind of text or flexbox alignment/justification setting.

If you feel like the suggestions do not cover your use case, can you please elaborate what exactly you want to use it for and provide some other possible use cases for it?

**Comment by jguddas** [comment]
![icon (40)](https://github.com/lucide-icons/lucide/assets/25524993/f556c6aa-263c-4298-b55e-752e92d50e7d) [source](https://lucide-studio.vercel.app/?value=%3Csvg++xmlns=%22http://www.w3.org/2000/svg%22++width=%2224%22++height=%2224%22++viewBox=%220+0+24+24%22++fill=%22none%22++stroke=%22currentColor%22++stroke-width=%222%22++stroke-linecap=%22round%22++stroke-linejoin=%22round%22%3E++%3Cpath+d=%22M11+12h6%22+/%3E++%3Cpath+d=%22M11+17h6%22+/%3E++%3Cpath+d=%22M11+7h6%22+/%3E++%3Cpath+d=%22M7+12h.01%22+/%3E++%3Cpath+d=%22M7+17h.01%22+/%3E++%3Cpath+d=%22M7+7h.01%22+/%3E++%3Crect+x=%223%22+y=%223%22+width=%2218%22+height=%2218%22+rx=%222%22+/%3E%3C/svg%3E)
