### ISSUE TITLE
v0.350+ breaks Tauri Beta

### ISSUE THREAD

**Issue by caseybaggz** [lucide-icons/lucide#1962]
### Package

- [ ] lucide
- [ ] lucide-angular
- [ ] lucide-flutter
- [ ] lucide-preact
- [ ] lucide-react
- [ ] lucide-react-native
- [X] lucide-solid
- [ ] lucide-svelte
- [ ] lucide-vue
- [ ] lucide-vue-next
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

0.350.0+

### Browser

- [ ] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [X] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [X] macOS
- [ ] Other/not relevant

### Description

Upgrading from 0.344.0 to anything above breaks the rendering of a Tauri Beta app via the following error:
```
Unexepected "<" in ArrowUp
```

### Steps to reproduce

1. Create a Tauri Beta build
2. Use `lucide-solid` & SolidJS
3. Import any icon
4. 🛑  Build breaks with error

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by karsa-mistmere** [comment]
Hi @caseybaggz,

Thanks for submitting a bug report, I've managed to reproduce and track this bug, the issue is with our Solid Start exports, which are in a JSX format (as necessary) but use a .js extension, which leads Tauri to mistakenly assume that they are vanilla JS, and they somehow end up being used. I've submitted a PR that will hopefully resolve this issue (I've already built and tested it).

**Comment by karsa-mistmere** [comment]
Hi @caseybaggz,

Can you confirm if the issue is resolved in the latest version?

**Comment by caseybaggz** [comment]
@karsa-mistmere fixed! Thanks so much!
