### ISSUE TITLE
X Logo (fka Twitter)

### ISSUE THREAD

**Issue by hanzalahwaheed** [lucide-icons/lucide#1985]
### Icon name

X

### Use cases

- Tons of websites have their X (fka Twitter) accounts on their landing pages.
- Currently any app using lucide is using the old logo (blue bird).
- Hence, we need to add a "X" representing the current twitter.

### Design ideas

![image](https://github.com/lucide-icons/lucide/assets/101456741/9398b86c-64fc-4542-b18a-bc20ee0d3b0b)

Source: https://icons8.com/icons/set/twitter-x

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by brandonmcconnell** [comment]
@karsa-mistmere Why was this closed? It's a rather essential icon, so I'm now having to turn to other icon libs and mix their icons into my codebase, which is fine, but why not add X?

**Comment by karsa-mistmere** [comment]
X is a brand logo and we do not accept any new brand logos because of copyright reasons, see our pinned issue at #670 

There's also a large notice about this in the icon request issue form:
![image](https://github.com/lucide-icons/lucide/assets/17746067/a050a921-9851-40b2-9cb9-58d2b55db93d)

This, and also because two mandatory checklist items were left unchecked:
![image](https://github.com/lucide-icons/lucide/assets/17746067/d92ba2c5-5e6f-48fd-9036-49cc68fa6426)

The former probably because this icon has already been requested on multiple occasions: #1468 #1528 #1561 #1717 #1490
