### ISSUE TITLE
X Icon (formerly twitter) request

### ISSUE THREAD

**Issue by sethshivam11** [lucide-icons/lucide#2232]
### Icon name

XLogo, XIcon, TwitterX

### Use cases

Since the twitter has changed its logo from bird to X and we don't have icon for that. So, we can create that.

### Design ideas

Svg: 
![x-social-media-black-icon](https://github.com/lucide-icons/lucide/assets/130232913/2ecdfcf4-d572-4b6a-8613-8ca5e3455061)

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by heymattiarighetti** [comment]
@jguddas why not planned? I also need it and I'm loading svgs manually instead of a simple lucide icons import (I used react icons only for that reason in the past...)

**Comment by karsa-mistmere** [comment]
See #670 #1468  #1528 #2220 #1561 #1717 #94 etc.

**Comment by heymattiarighetti** [comment]
@karsa-mistmere I see, thanks. Yet, you're cutting short on a problem that shouldn't be like this
They have their logos? Ok, don't adapt them to lucide icons style. Just give us the opportunity to embed brand icons along lucide ones without mixing external libraries

**Comment by karsa-mistmere** [comment]
> Just give us the opportunity to embed brand icons along lucide ones without mixing external libraries

Even if we wanted to, we simply cannot officially provide you with various brand icons, since they're protected by copyright.

If you really really really wanted to use Lucide to output these, you could grab the SVG code from simpleicons.org and use `createLucideIcon` to create a Lucide component, but be sure to override strokes with fills and add any extra necessary attributes, e.g.:

https://codesandbox.io/p/sandbox/objective-carson-htkrcr?utm_medium=sandpack&workspaceId=4ddbaddd-ab88-4029-91a2-e5be8ed85e45&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm0dtnyec00073b6ddk7j4q0q%2522%252C%2522sizes%2522%253A%255B100%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm0dtnyec00033b6ddg3sz4si%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm0dtnyec00043b6dgrizp542%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm0dtnyec00063b6dhpvef5yl%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm0dtnyec00033b6ddg3sz4si%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0dtnyec00023b6dvb455ejw%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Ficon.css%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A17%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A17%252C%2522endColumn%2522%253A1%257D%255D%257D%252C%257B%2522id%2522%253A%2522cm0dtob1200023b6drdu2jgxk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cm0dtnyec00033b6ddg3sz4si%2522%252C%2522activeTabId%2522%253A%2522cm0dtob1200023b6drdu2jgxk%2522%257D%252C%2522cm0dtnyec00063b6dhpvef5yl%2522%253A%257B%2522id%2522%253A%2522cm0dtnyec00063b6dhpvef5yl%2522%252C%2522activeTabId%2522%253A%2522cm0dtodkb000t3b6dd3nahkfh%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0dtnyec00053b6daay6va0b%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%252C%257B%2522type%2522%253A%2522SANDBOX_INFO%2522%252C%2522isCloud%2522%253Afalse%252C%2522id%2522%253A%2522cm0dtodkb000t3b6dd3nahkfh%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522cm0dtnyec00043b6dgrizp542%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cm0dtnyec00043b6dgrizp542%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by heymattiarighetti** [comment]
> > Just give us the opportunity to embed brand icons along lucide ones without mixing external libraries
> 
> Even if we wanted to, we simply cannot officially provide you with various brand icons, since they're protected by copyright.
> 
> If you really really really wanted to use Lucide to output these, you could grab the SVG code from simpleicons.org and use `createLucideIcon` to create a Lucide component, but be sure to override strokes with fills and add any extra necessary attributes, e.g.: [...]

thanks a lot, it worked!

**Comment by rohDevellopper** [comment]
The same thing happens to me, what I did was call an SVG. And problem solved: 
```
const XIcon = () => (
  <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
    <path d="M4 3h16c.6 0 1 .4 1 1v16c0 .6-.4 1-1 1H4c-.6 0-1-.4-1-1V4c0-.6.4-1 1-1zm9.5 10.2l4.2-6.2H16l-3.2 4.8L10 7h-1.7l4.3 6.5-4.3 6.5H9l3.3-4.9 3.4 4.9h1.6l-4.3-6.3z" />
  </svg>
);

// Social icons list
const socialIcons = [
  { name: 'X', icon: XIcon, path: null },
  { name: 'LinkedIn', icon: Linkedin, path: null },
  { name: 'Facebook', icon: Facebook, path: null },
  { name: 'GitHub', icon: Github, path: null }
];
```

**Comment by namerisibunker** [comment]
I made it for me, if you want to use it, just change it with whatever you need:



<style>
  .footer-icon-x {
    width: 24px;
    height: 24px;
    display: inline-block;
    color: #423435;               /* default color */
    transition: color 200ms ease; /* smooth hover */
  }
  .footer-icon-x:hover {
    color: #86512f;               /* hover color */
  }
</style>

<svg
  class="footer-icon-x"
  viewBox="0 0 16 16"
  fill="currentColor"
  xmlns="http://www.w3.org/2000/svg"
  aria-hidden="true"
>
  <path d="M12.6.75h2.454l-5.36 6.142L16 15.25h-4.937l-3.867-5.07-4.425 5.07H.316l5.733-6.57L0 .75h5.063l3.495 4.633L12.601.75Zm-.86 13.028h1.36L4.323 2.145H2.865z"/>
</svg>

**Comment by namerisibunker** [comment]
I made it for me, here it is if you want to use it, just change it with however you want:


```
<style>
  .footer-icon-x {
    width: 24px;
    height: 24px;
    display: inline-block;
    color: #423435;               /* default color */
    transition: color 200ms ease; /* smooth hover */
  }
  .footer-icon-x:hover {
    color: #86512f;               /* hover color */
  }
</style>

<svg
  class="footer-icon-x"
  viewBox="0 0 16 16"
  fill="currentColor"
  xmlns="http://www.w3.org/2000/svg"
  aria-hidden="true"
>
  <path d="M12.6.75h2.454l-5.36 6.142L16 15.25h-4.937l-3.867-5.07-4.425 5.07H.316l5.733-6.57L0 .75h5.063l3.495 4.633L12.601.75Zm-.86 13.028h1.36L4.323 2.145H2.865z"/>
</svg>

```
