### ISSUE TITLE
Request to add an icon to end call

### ISSUE THREAD

**Issue by sethshivam11** [lucide-icons/lucide#2332]
### Icon name

End call

### Use cases

This can be useful when developing a calling app (either video or audio).

### Design ideas

![Image](https://github.com/user-attachments/assets/e2c29626-2e79-41e4-a09d-a5521b780e16)

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by karsa-mistmere** [comment]
We aren't really likely to add this as an icon of its own in a way that's acceptable for this use case. In order to add a rotated variant, we would have to shrink it down considerably, making it break our 2px gap rule, and adjusting for that would make it completely out of proportion:

![image](https://github.com/user-attachments/assets/b24de356-be36-47cd-8040-bb7df887d0d5)


I'd recommend using `phone` and rotating it via a CSS transform, which will work perfectly well within a circular button:
![image](https://github.com/user-attachments/assets/0a0c7031-31e5-445b-905b-2baf7c8cbf78)
