### ISSUE TITLE
Request: Portal

### ISSUE THREAD

**Issue by NoobExploits** [lucide-icons/lucide#2439]
### Icon name

a portal

### Use cases

Im personally using it for my UI that has a teleports feature and I think a portal would be better than a map I guess

### Design ideas

something like the o in portal but idk im not a designer and i think yall could think of it way better
![portal logo](https://github.com/user-attachments/assets/3899f029-0a55-479a-9eb2-f30e58bb835b)

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I am not requesting an icon that includes religious, political imagery or hate symbols.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by karsa-mistmere** [comment]
Hi @NoobExploits,

There is a lack of use cases here, first of all, can you elaborate on what this teleports feature does? Do you mean a literal teleport like in Diablo?
![image](https://github.com/user-attachments/assets/2ba6a8a3-d54f-4d24-acf5-9efe57784ce5)

If so, since this use case is highly specific, can you please provide some other possible use cases for this icon?

**Comment by NoobExploits** [comment]
i kinda realized i dont need this so 😭
