### ISSUE TITLE
`Lucide-react` depend `prop-types` right?

### ISSUE THREAD

**Issue by PeterlitsZo** [lucide-icons/lucide#486]
## Prerequisites

* Version: ^0.16.28
* Are you running from source/master: emm... from npm?
* Are you using a released build: emmm...yes?
* Operating system: Linux - Manjaro
* Bits: 64-bits.

## Step to reproduce

*When I use it, it raises a error that it need prop-types. I resolve by just add it in my `package,json`. But I hope I do not need it.*

## Maybe Help

I think we can move `prop-types` in `lucide-react`'s `package.json` from `devDependencies` to `dependencies`. If you guys think I am right, Please tell me and I will give you a PR as soon as I can. Please.

**Comment by PeterlitsZo** [comment]
Hello?

**Comment by ericfennis** [comment]
@PeterlitsZo Sorry for the late reply. 
prop-types is added in the peerDependecies, same for react. Those dependecies will be installed when installing the package. We added it to devdependecies as well because we use this when we are developing as wel. peerDependecies won't be installed locally only in "package" form.

**Comment by PeterlitsZo** [comment]
I am not sure what happen, maybe just I use vite to instead of snowpack... Now I remove `prop-types` but no error raise... (If somebody else find it raise the same error, please comment with a link to your project, I'd like to help you)...

Thanks for your kindly help!!! I really like lucide!!! I hope I can help you with more PR in the future. Salut.
