### ISSUE TITLE
Filter is a reserved HTML element

### ISSUE THREAD

**Issue by felix-berlin** [lucide-icons/lucide#515]
## Prerequisites

* Version: 0.17.1
* Are you running from source/master: No
* Are you using a released build: No
* Operating system:  Win 11
* Bits: 64 bits

## Step to reproduce

- Add and use the filter icon
- Used inside a Nuxt v2 project

## Any message or error

- Do not use built-in or reserved HTML elements as component id: Filter

## Resources

![image](https://user-images.githubusercontent.com/17964384/155634660-53a31f27-367c-4548-87f9-ad38e9254b46.png)

**Comment by ericfennis** [comment]
@felix-berlin Thanks for reporting.
To fully reproduce this issue can you maybe provide a example project in a repo or maybe better a codesandbox/stackblitz?

**Comment by fdev** [comment]
If this needs to be fixed, it's not just _filter_. Other icons match SVG or HTML elements as well:

SVG elements: [circle](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/circle), [filter](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/filter)
HTML elements: [code](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/code), [menu](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/menu), [option](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option), [table](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table), [video](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video).

**Comment by ericfennis** [comment]
Hmm it's weird that this still happens.
I added an 'Icon' suffix a while ago in the [export template](https://github.com/lucide-icons/lucide/blob/37161048767fac5a24aa03c02f63467235917d9b/packages/lucide-vue/scripts/exportTemplate.js#L4)
From what I understand if you add this to name this should not be a problem. Because setting the name will change the component Id. But seems some SVG elements are ignored with this fix. Vue [ref issue](https://github.com/vuejs/vue/issues/7608#issuecomment-773230434)

[Codesandbox](https://codesandbox.io/s/lucide-vue-nuxt-p8ckju?file=/components/TestLucide.vue)
