### ISSUE TITLE
Update logo

### ISSUE THREAD

**Issue by johnletey** [lucide-icons/lucide#7]
I think it's a good idea to have a different visual identity to the official Feather project.

Here is a potential logo:

![logo](https://user-images.githubusercontent.com/62398724/84576692-9ee5da80-adae-11ea-8ee8-f34f000c8755.png)

It is a combination of the GitHub octicons [`repository`](https://primer.style/octicons/repo-24) icon (to represent the "community" part of this project) and the [`feather`](https://github.com/featherity/featherity/blob/master/icons/feather.svg) icon (to stay true to our parent project).

> [Figma](https://www.figma.com/file/eKbUawZFrwFkAe8SOzlP8D/featherity)

**Comment by locness3** [comment]
I'll leave this up to you.

**Comment by jletey** [comment]
Let’s go with the second option as both icons are from our icon-set.

I’m thinking about leaving this open so if anyone else has a suggestion they can submit it 😄

**Comment by ericfennis** [comment]
I was working on an Icon, I thought this maybe fit nice as a Logo. It's in the style like the feather logo.

I was thinking maybe we can change the name as wel, I like the name featherity because idea behind it: Feather + community.
But I experienced that pronouncing the name is quite hard. I most of the times pronounce it  as "feather+ ty" or "feather+ai+ty. 

Overall it's just an idea I want to share 😁.

![image](https://user-images.githubusercontent.com/11825403/92039429-5585a580-ed75-11ea-8f69-90e04db3c79b.png)

**Comment by johnletey** [comment]
Hmm @ericfennis, I like the ring of `Clover` 😁

And the icon is quite nice!

**Comment by ericfennis** [comment]
thanks, first I will add it as an icon!
