### ISSUE TITLE
can globally be lazy loaded in Vue3

### ISSUE THREAD

**Issue by spormeon** [lucide-icons/lucide#793]
Does anyone know if this can be lazy loaded in a global sense, we are using the import * as icons from "lucide-vue-next";  but want to lazy load the individual icons, dependant on page use, but still want to have the icons load globally, so as not to have to maintain dozens of individual calls per page etc?

**Comment by ericfennis** [comment]
Hmm I think this really hard to accomplish without doing individual calls for each icon. 

What you can try is creating one index file full of dynamic import for each icon. But that will result in individual calls.

May I ask why is not possible to individual import each icon?
Because the icons are formatted and optimized to small files and are tree-shakable by your bundler. Importing it won't impact your bundle drastically.

**Comment by spormeon** [comment]
it is impacting our bundle size as its about 235kib, when it could be down to a few kib, if they "LL",  i'll try this index page with dynamic imports idea, least that keeps them all in 1 file, so we dont have to think about imports for icons on every page

**Comment by spormeon** [comment]
@ericfennis not getting any luck with this idea, can you give me any pointers?  tried this and if try to LL it dont show the icon:
![index_js_—_statsadysis](https://user-images.githubusercontent.com/8503167/187050848-2733a5e2-fe13-4b24-a61f-db720641e7ed.png)

**Comment by ericfennis** [comment]
Looking at your imports I'm not sure if this is the right repository. The imports don't match our package name: 'lucide-vue-next'

If you want to use lucide, I think you should have something like this.

```js
const DollarSign = defineAsyncComponent(() =>
  import('lucide-vue-next/icons/dollar-sign')
)
```
