### ISSUE TITLE
ID card icon

### ISSUE THREAD

**Issue by nordowl** [lucide-icons/lucide#953]
## Icon Request

* Icon name: identification
* Use case: ID, passport, verification, KYC
* _Screenshots_ of similar icons: 
![Screenshot_3](https://user-images.githubusercontent.com/71926058/219497680-b10fd582-26e4-4df1-8b39-97a68c594590.png)
![Screenshot_4](https://user-images.githubusercontent.com/71926058/219497684-2f7611c8-af5c-4768-9529-ae4e3dbdc46d.png)
![Screenshot_1](https://user-images.githubusercontent.com/71926058/219497687-3553e8cd-5abe-46e9-94f4-4208856008f0.png)

**Comment by jguddas** [comment]
ID-Card is doable, passport is quite hard tho.
![](https://user-images.githubusercontent.com/25524993/219704856-b4c8e59c-56ae-4d76-a736-e3935e30d8df.png)

**Comment by nordowl** [comment]
I think having only an ID card is sufficient as it can generalize / abstract the topic of verification as a whole.

**Comment by karsa-mistmere** [comment]
I think for consistency's sake, this icon should have the exact same dimensions as `credit-card` (as do most real life ID and credit cards), but this will make the second design quite unfeasible, as it already violates some guidelines as it is.

I have the following proposals as compared to `credit-card`:
![image](https://user-images.githubusercontent.com/17746067/221934895-34c7055a-ead7-4214-9028-16f1fde9b4b3.png)
![image](https://user-images.githubusercontent.com/17746067/221934915-4cf25556-fb15-45f0-b8a0-d57752b7c1d1.png)

col 1: credit card
col 2 uses the user style from https://github.com/lucide-icons/lucide/issues/657
col 3 uses an abstract placeholder shape instead of a person
col 4 uses the head shape as already present in `accessibility`, `person-standing`, `bike` amongst others (using the same exception to the 2px rule as the icons mentioned).

**Comment by nordowl** [comment]
I personally like variant 2 and 3.

**Comment by jguddas** [comment]
v3 looks a bit like a microwave tbh.

I think v2 looks the best but the schoulders should be more squarish like v4.

**Comment by xnousnow** [comment]
I prefer v4 over v2. Also, it would be best if the text in v4 expands a bit.

**Comment by jguddas** [comment]
What about something like this: ![id-card](https://user-images.githubusercontent.com/25524993/227778013-b17599de-bde9-433c-abe8-01be25a19cc8.svg)

<img src="https://user-images.githubusercontent.com/25524993/227777972-bad3ce9d-cff2-450d-b5bb-10bb6bf0143f.svg" width="100%"/>

**Comment by nordowl** [comment]
> What about something like this: ![id-card](https://user-images.githubusercontent.com/25524993/227778013-b17599de-bde9-433c-abe8-01be25a19cc8.svg) or ![id-card (5)](https://user-images.githubusercontent.com/25524993/227779727-96a45862-021c-4efa-847c-48a1f14f1a96.svg) or ![id-card (6)](https://user-images.githubusercontent.com/25524993/227779989-f2588c57-a8ac-4ea8-ba80-3fa738561fe6.svg)?

I like 1 and 2, but I do think the persons body almost looks like a line of text

**Comment by ericfennis** [comment]
I think on 100% scale you don't see the angle of the line. I think we can better keep it straight then. 

I think the second one looks the best.
